### ISSUE TITLE
Tracking issue for speccing disallowed prerendering BC features

### ISSUE THREAD

**Issue by domenic** [jeremyroman/alternate-loading-modes#42]
The prerendering browsing contexts explainer, supplemented by [this Google doc](https://docs.google.com/document/d/1zY15k_wFTik2EoxBf3_RT7YjYpFMDaeNspy15n0rtww/edit#), lists all the APIs we want to restrict. This issue is meant to track actually speccing those restrictions, in checklist form.

For some of these (e.g. cross-origin isolated) the outcome may be "don't restrict"; we can check the box when we explicitly make that decision and include a note in the spec about it being permissions-controlled but still not restricted.

* Storage access
  * Synchronous key-value stores
    - [ ] Cookies
    - [ ] localStorage
    - [ ] sessionStorage
  * Asynchronous APIs
    - [ ] IndexedDB
    - [ ] Cache storage
    - [ ] File System Access's origin-private file system
    - [ ] Storage Foundation API
* Complicated not-quite storage things
  - [ ] Shared workers
  - [ ] Service workers
  - [ ] BroadcastChannel
  - [ ] Web locks
* Permissions API-controlled features ([registry](https://w3c.github.io/permissions/#permission-registry), but the registry is not up to date)
  - [x] Geolocation #36
  - [x] Notifications #36
  - [ ] Notifications from within a service worker
  - [ ] Push
  - [x] MIDI #36
  - [ ] Camera
  - [ ] Microphone
  - [ ] Speaker selection
  - [ ] Device info
  - [ ] Background fetch
  - [ ] Background sync
  - [ ] Bluetooth
  - [ ] Persistent storage
  - [ ] Ambient light sensor
  - [ ] Accelerometer
  - [ ] Gyroscope
  - [ ] Magnetometer
  - [ ] Clipboard read
  - [ ] Clipboard write
  - [ ] Display capture
  - [ ] NFC
  - [ ] Web USB
  - [ ] WebXR Spatial Tracking
  - [x] Idle detection #36
  - [x] File System Access (not the origin-private subset) #36
* Not-allowed-by-default permissions policy features ([registry](https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md)). Omitting ones already in permissions API list.
  * Asynchronous (despite not being permission-gated)
    - [ ] Battery status
    - [x] Fullscreen #36
    - [ ] Picture-in-picture
    - [ ] Encrypted media extensions
    - [ ] Web Authentication public key credentials get
    - [ ] Wake lock
    - [ ] HID
    - [x] Serial
    - [ ] Web Share
    - [ ] Navigation override
  * Synchronous/no obvious JS entry point
    - [ ] Autoplay
    - [ ] Cross-origin-isolated
    - [x] Payment request API
    - [ ] Gamepad
    - [ ] Conversion measurement API
  * Can't tell; explainer doesn't have enough detail
    - [ ] Trust token redemption
* Features currently only controllable via sandbox=""
  * Asynchronous
    - [ ] Pointer lock
    - [ ] Orientation lock
    - [x] window.open()
    - [x] PresentationRequest #36
    - [x] Downloads (e.g. `<a download>.click()`)
    - Modal system dialogs (not `<dialog>`)
      - [x] alert / print: no feedback to script
      - [x] confirm / prompt: return value consumed by script
      - [x] beforeunload

**Comment by mfalken** [comment]
Implementation note for autoplay: Chromium will likely defer loading the data during prerendering, to make it less costly if it's not used. That's currently what we're doing for NoStatePrefetch.

**Comment by domenic** [comment]
Notes for next steps:

- We are focused on same-origin prerendering first. So, I believe everything under "Storage access" does not need restrictions, for now.
- I think the same is true for "Complicated not-quite storage things", but I am not 100% sure.
- Currently nothing is specced to cancel prerender (i.e., discard the entire prerendering browsing context). Chromium definitely does this for some features, and we should probably spec such cases.
- In general, it's unclear how well what is specced so far (i.e., the currently-checked boxes) match up with Chromium's implementation and the corresponding web platform tests. This could include large mismatches (e.g., Chromium cancels, the spec delays) or small ones (e.g., the spec delays some potential early errors, but Chromium throws them; see https://github.com/WICG/nav-speculation/pull/45#discussion_r581469186 and #61 for some discussion).

**Comment by nyaxt** [comment]
I briefly synced up with @nhiroki on this. He recommended to start from "Not-allowed-by-default permissions policy features" which should all be implicitly disallowed.

**Comment by noamr** [comment]
IndexedDB PR: https://github.com/WICG/nav-speculation/pull/108

@domenic anyway I could edit the checklist? It's in a comment so I can't right now.

**Comment by noamr** [comment]
> The prerendering browsing contexts explainer, supplemented by [this Google doc](https://docs.google.com/document/d/1zY15k_wFTik2EoxBf3_RT7YjYpFMDaeNspy15n0rtww/edit#), lists all the APIs we want to restrict. This issue is meant to track actually speccing those restrictions, in checklist form.
> 
> For some of these (e.g. cross-origin isolated) the outcome may be "don't restrict"; we can check the box when we explicitly make that decision and include a note in the spec about it being permissions-controlled but still not restricted.
> 
> * Storage access
>   
>   * Asynchronous APIs
>     
>     * [ ]  IndexedDB
>     * [ ]  Cache storage
>     * [ ]  File System Access's origin-private file system
>     * [ ]  Storage Foundation API
> * Complicated not-quite storage things
>   
>   * [ ]  Shared workers
>   * [ ]  Service workers
>   * [ ]  BroadcastChannel
>   * [ ]  Web locks

Any reason to have something other than `{{[DelayWhilePrerendering]}}` for all of the above?

**Comment by noamr** [comment]
>     * [ ]  Autoplay
The spec says: "Queue a media element task given the element to fire an event named play at the element." [here])https://html.spec.whatwg.org/#ready-states:queue-a-media-element-task-8). Isn't this enough? AFAIU this task would be delayed until the page is activated

**Comment by noamr** [comment]
> Notes for next steps:
> 
> * We are focused on same-origin prerendering first. So, I believe everything under "Storage access" does not need restrictions, for now.

I think storage access needs to have `DelayWhilePrerendering`. Otherwise the active page and prerendering page might be trying to access the same resources. This might be OK if we see prerender as "open in a new tab and navigate later" though.

**Comment by domenic** [comment]
> AFAIU this task would be delayed until the page is activated

No, tasks run inside prerendering browsing contexts.

> Otherwise the active page and prerendering page might be trying to access the same resources. This might be OK if we see prerender as "open in a new tab and navigate later" though.

The latter aligns with my thinking; I don't think accessing the same resources in multiple browsing contexts (prerendering or not) is a problem. But, @nyaxt and @nhiroki should confirm from an implementation perspective.

**Comment by noamr** [comment]
> > AFAIU this task would be delayed until the page is activated
> 
> No, tasks run inside prerendering browsing contexts.
> 
> > Otherwise the active page and prerendering page might be trying to access the same resources. This might be OK if we see prerender as "open in a new tab and navigate later" though.
> 
> The latter aligns with my thinking; I don't think accessing the same resources in multiple browsing contexts (prerendering or not) is a problem. But, @nyaxt and @nhiroki should confirm from an implementation perspective.

The WPTs seem to test that localStorage and IDB do work. So maybe this is a no-op in terms of same-origin, at least for now.

**Comment by noamr** [comment]
> > AFAIU this task would be delayed until the page is activated
> 
> No, tasks run inside prerendering browsing contexts.
Got it. Maybe the place to put it would be [here]https://html.spec.whatwg.org/#playing-the-media-resource:current-playback-position-9).

"When a media element is potentially playing and its Document is a fully active Document, its current playback position must increase monotonically"

IIUC, a "prerendered" document still considered "fully active" (which is somewhat confusing), so that would maybe be a good place to monkey-patch.

**Comment by domenic** [comment]
I guess the question is whether we want to:

1. Disallow autoplay, but allow playing in other ways. (Presumably in this case we'd mute any audio, even if the timeline advances...)
2. Disallow playing at all
3. Allow playing, but don't advance the playback position while playing.

You seem to be suggesting (3), but I feel like either (1) or (2) would be better.

**Comment by noamr** [comment]
> I guess the question is whether we want to:
> 
> 1. Disallow autoplay, but allow playing in other ways. (Presumably in this case we'd mute any audio, even if the timeline advances...)
> 2. Disallow playing at all
> 3. Allow playing, but don't advance the playback position while playing.
> 
> You seem to be suggesting (3), but I feel like either (1) or (2) would be better.

Yea, I'm suggesting 3. I don't think any website would expect playback to happen in a speculatively-prerendered page. Though (2) is also good AFAIC.

Web pages who really want to do this can "seek" rather than "play". But I'll try to figure out what's in the current implementation.

**Comment by noamr** [comment]
The problem with (2) is that a page that had playing support before would now not have it just because it happened to have been prerendered.

I think "delayed playing" (which is essentially (3)) is what users expect - maybe some of the metadata of the audio/video was loaded, but the playback will start advancing in practice only when the page is activated.

**Comment by domenic** [comment]
I think I'm convinced by your reasoning!

**Comment by noamr** [comment]
> I think I'm convinced by your reasoning!

https://github.com/WICG/nav-speculation/pull/109

**Comment by noamr** [comment]
> I briefly synced up with @nhiroki on this. He recommended to start from "Not-allowed-by-default permissions policy features" which should all be implicitly disallowed.

Any reason why they are disallowed rather than deferred?

**Comment by noamr** [comment]
A lot has been done on this, I don't think there is much left.

> 
> * Storage access
>   
>   * Synchronous key-value stores
>     
>     * [ ]  Cookies
>     * [ ]  localStorage
>     * [ ]  sessionStorage
>   * Asynchronous APIs
>     
>     * [ ]  IndexedDB
>     * [ ]  Cache storage
>     * [ ]  File System Access's origin-private file system
>     * [ ]  Storage Foundation API
> * Complicated not-quite storage things
>   
>   * [ ]  Shared workers
>   * [ ]  Service workers
>   * [ ]  BroadcastChannel
>   * [ ]  Web locks

I don't think any of the above should have restrictions, not sure what needs to be done here.

> * Permissions API-controlled features ([registry](https://w3c.github.io/permissions/#permission-registry), but the registry is not up to date)
>   
>   * [x]  Geolocation [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
>   * [x]  Notifications [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)

>   * [ ]  Notifications from within a service worker

See  https://github.com/WICG/nav-speculation/issues/44


>   * [x]  Push
>   * [x]  MIDI [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
>   * [x]  Camera
>   * [x]  Microphone
>   * [x]  Speaker selection
>   * [ ]  Device info

Not sure which API this refers to.

>   * [x]  Background fetch
>   * [x]  Background sync
>   * [x]  Bluetooth
>   * [x]  Persistent storage
>   * [x]  Ambient light sensor [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Accelerometer [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Gyroscope [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Magnetometer [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Clipboard read [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Clipboard write [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Display capture
>   * [x]  NFC [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>   * [x]  Web USB
>   * [x]  WebXR Spatial Tracking
>   * [x]  Idle detection [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
>   * [x]  File System Access (not the origin-private subset) [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
> * Not-allowed-by-default permissions policy features ([registry](https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md)). Omitting ones already in permissions API list.
>   
>   * Asynchronous (despite not being permission-gated)
>     
>     * [x]  Battery status [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>     * [x]  Fullscreen [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
>     * [x]  Picture-in-picture [Introduce "implicitly restricted APIs". #62](https://github.com/WICG/nav-speculation/pull/62)
>     * [x]  Encrypted media extensions
>     * [x]  Web Authentication public key credentials get
>     * [x]  Wake lock [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45) [Introduce "implicitly restricted APIs". #62](https://github.com/WICG/nav-speculation/pull/62)
>     * [x]  HID
>     * [x]  Serial
>     * [x]  Web Share [Restrict more disurptive features #45](https://github.com/WICG/nav-speculation/pull/45)
>     * [ ]  Navigation override

Not sure which API this refers to.

>   * Synchronous/no obvious JS entry point
>     
>     * [x ]  Autoplay
>     * [x]  Cross-origin-isolated [cross-origin-isolated #52](https://github.com/WICG/nav-speculation/issues/52)
>     * [x]  Payment request API
>     * [x]  Gamepad [Specify restrictions on screen orientation and gamepads #53](https://github.com/WICG/nav-speculation/pull/53)
>     * [ ]  Conversion measurement API
>   * Can't tell; explainer doesn't have enough detail
>     
>     * [ ]  Trust token redemption

From the explainer I don't think this needs special restrictions.

> * Features currently only controllable via sandbox=""
>   
>   * Asynchronous
>     
>     * [x]  Pointer lock [Specify restrictions on screen orientation and gamepads #53](https://github.com/WICG/nav-speculation/pull/53)
>     * [x]  Orientation lock [Specify restrictions on screen orientation and gamepads #53](https://github.com/WICG/nav-speculation/pull/53)
>     * [x]  window.open()
>     * [x]  PresentationRequest [Spec some initial permissions check delays #36](https://github.com/WICG/nav-speculation/pull/36)
>     * [x]  Downloads (e.g. `<a download>.click()`)
>     * Modal system dialogs (not `<dialog>`)
>       
>       * [x]  alert / print: no feedback to script
>       * [x]  confirm / prompt: return value consumed by script
>       * [x]  beforeunload

**Comment by jeremyroman** [comment]
> I don't think any of the above should have restrictions, not sure what needs to be done here.

I assume this refers specifically to the case of same-origin prerendering, right? The cross-origin case will need some interventions in the storage space, though of course this isn't the only spec change that will be needed for the cross-origin case.

**Comment by noamr** [comment]
> > I don't think any of the above should have restrictions, not sure what needs to be done here.
> 
> 
> 
> I assume this refers specifically to the case of same-origin prerendering, right? The cross-origin case will need some interventions in the storage space, though of course this isn't the only spec change that will be needed for the cross-origin case.

Yes, referring only to same-origin.

**Comment by domenic** [comment]
I think we're missing speech synthesis: https://wicg.github.io/speech-api/#dom-speechsynthesis-speak

**Comment by noamr** [comment]
Regarding workers (dedicated + shared) - the spec currently allows them while the implementation delays them.
The reasoning behind the implementation decision AFAIU is to prevent prerendered pages from consuming too much resources, and workers are usually not part of the loading process, which is what prerender is designed for.

I tend to agree with the direction of allowing things in the prerender phase that are commonly relevant to loading rather than any general purpose browser feature.

@domenic, @jeremyroman  WDYT?

**Comment by noamr** [comment]
> I think we're missing speech synthesis: https://wicg.github.io/speech-api/#dom-speechsynthesis-speak

https://github.com/WICG/nav-speculation/pull/127

**Comment by domenic** [comment]
I am a bit worried that will hurt worker-heavy application architectures, but I think delaying is a good conservative starting point. Furthermore I think starting with delaying them per-spec is a good idea for interop. And then later we could loosen it to implementation-defined if we got feedback that different browsers wanted to experiment with different policies.

**Comment by noamr** [comment]
> I am a bit worried that will hurt worker-heavy application architectures, but I think delaying is a good conservative starting point. Furthermore I think starting with delaying them per-spec is a good idea for interop. And then later we could loosen it to implementation-defined if we got feedback that different browsers wanted to experiment with different policies.

Yea I think the direction (as seen also in the initial implementation) is to allow less, defer more at the first phase, to focus on loading, and then slowly open more stuff.

**Comment by nhiroki** [comment]
What about worklets (audio, animation, paint etc)? I wonder if we could defer them as well.

I need to check current behavior in Chromium, but I suspect they could just work in prerendered pages. I'll modify the behavior based on a consensus in the spec.

**Comment by noamr** [comment]
> What about worklets (audio, animation, paint etc)? I wonder if we could defer them as well.
> 
> 
> 
> I need to check current behavior in Chromium, but I suspect they could just work in prerendered pages. I'll modify the behavior based on a consensus in the spec.

As far as animation/paint, I don't think they need special treatment since the rendering pipeline will not call them- so loading them is ok and nothing needs to suspend them. I think the same goes for audio but need to verify

**Comment by domenic** [comment]
Yes, I think that's a good idea!
